### ISSUE TITLE
Feature suggestion: Export Context

### ISSUE THREAD

**Issue by christikaes** [EmaSuriano/react-scroll-section#32]
I am using dynamic tabs with a UI Library for rendering them, however, I need to be able to re-render when the contents of the sections change. It would be great if I could do a `useContext` to get more details. 

```js
export { ScrollingProvider, Section, SectionLink, SectionLinks, >>ScrollContext<< };
```

**Comment by christikaes** [comment]
Or actually it might be cleaner to export a hook that can be used to get all the section links:
```js
const sectionLinks = useSectionLinks()
```

**Comment by EmaSuriano** [comment]
Yeah I think exporting the context makes sense in case you want to use `React.useContext`

**Comment by EmaSuriano** [comment]
The context is now being exported in `v2.1.0`.
